# Generated by Django 5.1.6 on 2025-02-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_category_name_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
